spring:
  application:
    name: user-service
#  kafka:
#    bootstrap-servers: 192.168.216.128:9092
#    consumer:
#      group-id: user-service
#  cloud:
#    bus:
#      enabled: true
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: refresh,hystrix.stream
#Hystrix
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default: #全局配置，feignclient#method(param)
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 15000
    OrderServiceFeignClient#orders():
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 10
    OrderServiceFeignClient#insert():
      exection:
        isolation:
          strategy: THREAD
  threadpool:
    order-service:
      coreSize: 2
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800

#配置随机数生成
env: ${random.long}
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000