spring:
  application:
    name: order-service
#  kafka:
#    bootstrap-servers: 192.168.216.128:9092
#    consumer:
#      group-id: user-service
#  cloud:
#    bus:
#      enabled: true
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: refresh